name: 'CargoVersionBump'
description: 'Bump version of a Rust Cargo based project.'
author: 'Yuri6037'
inputs:
  mode:
    required: false
    description: 'get to return current crate name and version, set to check and apply the new provided version if it is greater than the current one'
    default: 'get'
  release-branch:
    required: false
    description: 'name of the release branch'
    default: null
  multi:
    required: false
    description: 'set to true if the repository has multiple Cargo crates, in which case multiple /version can be used, each with the directory name as second argument'
    default: false
  token:
    required: true
    description: 'the GitHub Actions token'
  cwd:
    required: false
    description: 'working directory of Cargo.toml'
    default: '.'
outputs:
  name:
    description: 'crate name'
  version:
    description: 'crate version'
runs:
  using: 'node16'
  main: 'dist/index.js'
